apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-cert
spec:
  secretName: myapp-tls
  issuerRef:
    name: zerossl-issuer
    kind: ClusterIssuer
  commonName: aviv.doorloop.info
  dnsNames:
    - aviv.doorloop.info
  solvers:
    - http01:
        ingress:
          class: nginx
