apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-cert
spec:
  secretName: myapp-tls
  issuerRef:
    name: zerossl-issuer
    kind: ClusterIssuer
  commonName: aviv.doorloop.info
  dnsNames:
    - aviv.doorloop.info
  solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIASGNC4G66Q6Y3ZHXA
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
