apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-issuer
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: aharuzi@doorloop.com
    privateKeySecretRef:
      name: zerossl-account-key
    externalAccountBinding:
      keyID: J5ZBxctZOW_W-634B5ytUA
      keySecretRef:
        name: zerossl-eab-secret
        key: eab-hmac-key
    solvers:
      - dns01:
          route53:
            region: us-east-1
            secretAccessKeySecretRef:
              name: ''
        selector:
          dnsZones:
            - develop.doorloop.com
