apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myapp-ingress
  namespace: your-namespace
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`aviv.doorloop.info`)
      kind: Rule
      services:
        - name: myapp-service
          port: 80
      middlewares:
        - name: redirect-to-https
  tls:
    certResolver: zerossl
